---
#The Ammount of time that you wish for the MOTD Delay.
#This doesn't make the client's query change,
#this effects the ammount of time the server sends the message.
#Default: 100
MOTD Delay: 5

#Here you can set if you want the shuffle on, or off.
#It is required to use quotations. :D
#Default: "off"
MOTD Shuffle: "off"

#The MOTD Messages.
#You can add to as much as you like! 
#Just make sure you copy it correctly. 
MOTD Message:
    - "§l§a• §cWelcome To §eKnight§fGhost"
    - "§l§a• §cPvP"
    - "§l§a• §eBoss"
    - "§l§a• §eSeason§9Pass"
    - "§l§a• §eQuest"
    - "§l§a• §eDrop"
    - "§l§9Season§a 2"
...