api-key: "a2NEZJ6Ka8Zu0TjpTyq6SkjQ2K00Xqd8eC" # API Key from https://minecraftpocket-servers.com/servers/manage/.
commands:
    # Commands to be executed when a player claims their vote.
    # They should not include the first "/" and they should be encased in quotes.
    # It is recommended to encase the username variable in escaped quotes (\") to make sure it
    #  is sent as one argument to the command to ensure they get all of their rewards.
    # List of useable variables:
    #  {username}: The player's in game username
    #  {displayname}: The player's display/nick name
    #  {x}: The player's X coordinate
    #  {y}: The player's Y coordinate
    #  {z}: The player's Z coordinate
    - "say §a§lCảm ơn người chơi §c{username} §a§lđã vote cho server!"
    - "title \"{username}\" title &aVote"
    - "title \"{username}\" subtitle &7cảm ơn đã vote!"
    - "key Vote \"{username}\" 1"
    - "givemoney \"{username}\" 1000"

# If droprewards is true, rewards will be dropped on the floor if a player's inventory is full
# If droprewards if false, rewards will dissapear if a player's inventory is full
droprewards: true
items:
    # Items to be given to a player when they claim their vote.
    # They should follow the format: "item_name:meta:amount:name:enchant_name:enchant_level".
    #  "name" can either be a custom name, or "default" to have no custom name.
    #  "item_name", "meta", "amount" & "name" must all come before any enchantments.
    #  "enchant_name:enchant_level" can be repeated as many times as you want.
    # Enchantments from PiggyCustomEnchants are also supported, use them the same as regular enchants.
    # They should also always be encased in quotes to make sure they get parsed properly.
    - "steak:0:64:§l§a§oBò Hảo Hán:unbreaking:2"
    - "diamond:0:1:§l§aRuby:unbreaking:2"

messages:
    info:
        title: "&aThis server's vote information:"
        content: "&aUptime: {uptime}\n&aScore: {score}\n&aRank: {rank}\n&aVotes: {votes}\n&aFavorited: {favorited}\n&aComments: {comments}"
    noperms: "&cYou do not have permission to use this command."
    reload:
        success: "&aYou have reloaded the server's vote configuration."
    top:
        novoters: "&cCác vote nhiều nhất của Server."
        title: "&aTop voter tuần này:"
        format: "&a{place}. {username}: {votes}"
    vote:
        alreadyclaimed: "&c[L Ỗ I] Bạn đã nhận quà rồi."
        alreadyprocessing: "&cVote của bạn đã được xử lý."
        claimed: "&aCảm ơn bạn đã vote cho server."
        error: "&cKhông thể xác nhận vote của bạn, vui lòng thử lại sau."
        notvoted: "&cBạn chưa vote."
        processing: "&aVote của bạn đang được xử lý, vui lòng đợi."
        usage:
            notplayer: "&cUse '/vote <info|reload|top>'."
            other: "&cUse '/vote [info|top]."
            reloadperm: "&cUse '/vote [info|reload|top]."