# Configuration file for SkyBlockUI
# Made by TheRealKizu (https://github.com/TheRealKizu)

# WARNING: Do not change the option below! For internal use only.
config-version: 1.0

# Options:
# skyblock - If you want to use the SkyBlock plugin by QiantQuartz.!
skyblock-plugin: "skyblock"