#==========================================#
#Config File for VecnaLeaderboards
#==========================================#
CONFIG_VERSION: 5
#====================================================================================#


#How often do you want all leaderboards to update to latest stats? (in seconds)
leaderboard-timer: 30


#Config the title to the text you want for it to display at the top for each statistic leaderboard.
#Use "&" for colors

kills: "&l&l| Kills Leaderboard |"

streaks: "&l&l| Kill Streaks Leaderboard |"

deaths: "&l&l| Deaths Leaderboard |"

levels: "&l&l| Levels Leaderboard |"

kdr: "&l&l| KDR Leaderboard |"

money: "&l&l| Money Leaderboard |"

  
#Top rankings, put 10 and only top 10 players on the leaderboard will be shown. 20 will result to top 20 and so on.
leaderboard-top-length: 10

#If you want to have EconomyAPI Support enabled leave it to true (You still have to create the leaderboard yourself)
#If you do not want to have EconomyAPI Support enabled set it to false

topmoney-leaderboard: true

#========================================================================#
# Levels System based on Kills from each player and rewards configuration
#========================================================================#

# Be sure you follow the configuration pattern or else you will likely face errors.
# You do not HAVE to add rewards per level but it is required to not skip levels (numbers) or else you might run through errors.

#Format for each levels
# Level Number:
#   kills: Amount of kills required to reach to the level
#   commands(OPTIONAL): The command that will and should be executed once the player has leveled up

#Variables supported you can use for rewards..
# {kills}- Number of kills
# {streak} - Kill streaks
# {deaths} - Number of deaths
# {p} - Player's username
# {level} - The player's level

#More variables will be supported soon

levels-settings:
  1:
    kills: 2
    cmds:
      - "tell {p} You have successfully reached level 1!"
      - "say {p} has successfully reached level 1!"
  2:
    kills: 4
    cmds:
      - "tell {p} You have successfully reached level 2!"
      - "say {p} has successfully reached level 2!"

#====================================================================================#
